definitions:
  services:
    postgres:
      image: postgres:9.6
      environment:
        POSTGRES_DB: ara
        POSTGRES_USER: ara
        POSTGRES_PASSWORD: ara
  steps:
    - step: &unit-tests
        name: Unit tests
        image: golang:1.12
        script:
          - export TZ=Europe/Paris LANG=en_US.UTF-8 LANGUAGE=en_US:en LC_ALL=en_US.UTF-8

          - apt-get update
          - mkdir -p /usr/share/man/man1 /usr/share/man/man7
          - export PACKAGES="build-essential ruby-dev libpq-dev libxml2-dev zlib1g-dev git-core postgresql-client-common"
          - export BUNDLER_VERSION="2.0.1"
          - apt-get -y install --no-install-recommends locales $PACKAGES
          - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && locale-gen
          - gem install bundler:$BUNDLER_VERSION

          # FIXME
          - export BASE_PATH="${GOPATH}/src/bitbucket.org/enroute-mobi"
          - mkdir -p ${BASE_PATH}
          - export IMPORT_PATH="${BASE_PATH}/ara"
          - ln -s ${PWD} ${IMPORT_PATH}
          - cd ${IMPORT_PATH}

          - export GO111MODULE="on"
          - go get -d -v ./...

          - bundle install --jobs 4 --deployment

          - export ARA_DB_NAME=ara ARA_DB_USER=ara ARA_DB_PASSWORD=ara ARA_DB_HOST=localhost
          - export ARA_CONFIG=$PWD/config
          - ./ci.sh
        services:
          - postgres

pipelines:
  default:
    - step: *unit-tests

  branches:
    master:
      - step: *unit-tests
      - step:
          name: Build Docker
          image: google/cloud-sdk:latest
          caches:
            - docker
          services:
            - docker
          script:
            - ./script/bitbucket-gcloud-configure-docker.sh
            - ./script/bitbucket-build-docker.sh
      - step:
          name: Deploy to test
          image: google/cloud-sdk:latest
          deployment: test
          script:
            - git clone $(echo $BITBUCKET_GIT_SSH_ORIGIN | sed 's/.git$/-env.git/') env
            - env/deploy.sh
            - pipe: atlassian/datadog-send-event:1.0.1
              variables:
                API_KEY: $DATADOG_KEY
                TITLE: "Build ${BITBUCKET_BUILD_NUMBER} deployed on ara ${BITBUCKET_DEPLOYMENT_ENVIRONMENT}"
      - step:
          name: Deploy to staging
          image: google/cloud-sdk:latest
          deployment: staging
          trigger: manual
          script:
            - git clone $(echo $BITBUCKET_GIT_SSH_ORIGIN | sed 's/.git$/-env.git/') env
            - env/deploy.sh
            - pipe: atlassian/datadog-send-event:1.0.1
              variables:
                API_KEY: $DATADOG_KEY
                TITLE: "Build ${BITBUCKET_BUILD_NUMBER} deployed on ara ${BITBUCKET_DEPLOYMENT_ENVIRONMENT}"
      - step:
          name: Deploy to production
          image: google/cloud-sdk:latest
          deployment: production
          trigger: manual
          script:
            - git clone $(echo $BITBUCKET_GIT_SSH_ORIGIN | sed 's/.git$/-env.git/') env
            - env/deploy.sh
            - pipe: atlassian/datadog-send-event:1.0.1
              variables:
                API_KEY: $DATADOG_KEY
                TITLE: "Build ${BITBUCKET_BUILD_NUMBER} deployed on ara ${BITBUCKET_DEPLOYMENT_ENVIRONMENT}"
      - step:
          name: Build Debian package
          caches:
            - docker
          services:
            - docker
          script:
            - export IMAGE_NAME=$BITBUCKET_REPO_SLUG-$BITBUCKET_BRANCH-debian-build
            - docker build -f Dockerfile.debian -t $IMAGE_NAME .
            - docker run -v $PWD/target:/target -e BUILD_NUMBER=${BITBUCKET_BUILD_NUMBER} $IMAGE_NAME
          artifacts:
            - target/*.deb
      - step:
          name: Publish Debian package
          deployment: gemfury
          trigger: manual
          script:
            - export PACKAGE_FILE=`ls -1 target/*.deb`
            - echo "Publish package $PACKAGE_FILE on Gemfury"
            - curl -F package=@$PACKAGE_FILE https://$GEMFURY_TOKEN@push.fury.io/enroute/
